# Set this website's info
# Change "speedmc" to your GitHub username
# Change "website" to your repository name
url: "https://speedmc.ml"
baseurl: "/website"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2022
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: SpeedMC
serverDescription: A Java-Bedrock Crossplay Minecraft server, where we have lots of fun!
serverIP: play.speedmc.ml Bedrock Port:23620
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/znfJdfRmaP
discordServerID: 822930403249356820
discordChannelID: 82293040356781791


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
